# from web development in go "Databases and SQL"
#
db: # service name
  image: postgres:17-bullseye
  restart: always 
  environment: 
    POSTGRES_USER: mylladmin
    POSTGRES_PASSWORD: ${PG_ADMIN_PW}
    POSTGRES_DB: myll
  ports:
    - 5432:5432 # here:container
  command:
    ["postgres", "-c", "log_duration = on", "-c", "log_min_duration_statement=0", "-c", "log_statement=all"]

  # config file is here:
  # /var/lib/postgresql/data/postgresql.conf
  # sed -i "s/#log_min_duration_statement = -1/log_min_duration_statement = 0/" /var/lib/postgresql/data/postgresql.conf

